# Generated by Django 5.0 on 2025-09-15 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='hearted_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
